// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlnyqkfaqrkdccymozzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsbnlxa2ZhcXJrZGNjeW1venp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njg5MzksImV4cCI6MjA2NTU0NDkzOX0.Jnre450HJ85umi5f3pqUYqRieOepLsV8M6oxI9HR-5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);